language: node_js

node_js:
  - 9

env:
  - NODE_ENV=development

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

before_install:
  - npm version patch

install:
  - yarn install
  - yarn run build-storybook

before_deploy:
  - git add package.json
  - git remote add origins https://${GITHUB_TOKEN}@github.com/Yukioru/ui-98.git > /dev/null 2>&1
  - git push --all --set-upstream origins master

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: storybook-static
    on:
      branch: master

  - provider: npm
    email: "obt195@gmail.com"
    api_key: $NPM_TOKEN