language: node_js

node_js:
  - 9

env:
  - NODE_ENV=development

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

cache: yarn

before_install:
  - npm version patch

install:
  - yarn install
  - yarn run build-storybook

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: storybook-static
    on:
      branch: master

  - provider: npm
    email: "obt195@gmail.com"
    api_key: $NPM_TOKEN